---
- name: Create a login user
  ansible.builtin.user:
      name: deployer
      password: '$6$iMNClsUEOVAFcGs0$f/siPQ9SnhjWRekhTLRxZIZWWmWnz5lmlfQ846znys9nyBujw1gDIyK8nc0IHdVesHYBGFZyhO3qRlvGWch4p/'
      groups: 
       - sudo
      state: present
      shell: /bin/bash      
      system: no            
      createhome: yes        
      home: /home/deployer
  
- name: Creates directory
  ansible.builtin.file:
    path: /home/deployer/.ssh
    state: directory
    mode: '0700'
    owner: deployer

- name: Create a new file with permissions
  ansible.builtin.file:
      path: "/home/deployer/.ssh/authorized_keys"
      state: touch
      mode: '0600'

- name: Copy Public key
  ansible.builtin.copy:
      src: "/root/.ssh/authorized_keys"
      dest: "/home/deployer/.ssh"

- name: Setup alternate sshd config
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{ item.key }} {{item.value}}"
    state: present
  with_dict: '{{ sshd_config }}'
  notify: Restart ssh service 
   

- name: Copy ssh banner file
  copy:
    src: ssh_banner
    dest: /etc/issue



    
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install basic tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
 





